steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'index.html', 'gs://musica-frontend-test/index.html']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['setmeta', '-h', 'Cache-Control:no-cache, max-age=0', 'gs://musica-frontend-test/index.html']

timeout: '120s'
